# -*- coding: utf-8 -*-
"""bankusecase.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MHVNNy5rTP6k0oQDTQ0yhVmz3ElbE0wt
"""

class BankAccount:
    def __init__(self, account_number, pin):
        self.account_number = account_number
        self.pin = pin
        self.balance = 0

    def deposit(self, amount):
        if amount > 0:
            self.balance += amount
            print(f"Deposited ${amount}. New balance is ${self.balance}")
        else:
            print("Invalid amount for deposit.")

    def withdraw(self, amount, entered_pin):
        if entered_pin != self.pin:
            print("Incorrect PIN. Withdrawal denied.")
            return

        if amount > 0 and self.balance >= amount:
            self.balance -= amount
            print(f"Withdrawn ${amount}. New balance is ${self.balance}")
        else:
            print("Insufficient funds or invalid amount for withdrawal.")

    def check_balance(self):
        print(f"Your current balance is ${self.balance}")

# Example usage:
account = BankAccount("1234567890", "1234")

# Deposit money
account.deposit(500)

# Check balance
account.check_balance()

# Withdraw money with PIN verification
account.withdraw(200, "1234")

# Incorrect PIN attempt for withdrawal
account.withdraw(100, "0000")