# -*- coding: utf-8 -*-
"""Visualisation_Scifor.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15vlxD9NLJO6nqNHzkbLu_TFiBkRPdbSd
"""

from sklearn.datasets import load_iris
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the Iris dataset
iris_data = load_iris()

# Convert the dataset into a pandas DataFrame
iris = pd.DataFrame(data=iris_data.data, columns=iris_data.feature_names)
iris['target'] = iris_data.target

# Map target names for better visualization
iris['species'] = iris['target'].map({0: 'setosa', 1: 'versicolor', 2: 'virginica'})

# Bar Chart
plt.figure(figsize=(8, 6))
bar_colors = {'setosa': 'red', 'versicolor': 'blue', 'virginica': 'green'}
iris['species'].value_counts().plot(kind='bar', color=iris['species'].map(bar_colors))
plt.title('Bar Chart')
plt.xlabel('Species')
plt.ylabel('Count')
plt.show()

# Pie Chart
plt.figure(figsize=(8, 6))
pie_colors = ['orange', 'lightblue', 'lightgreen']
iris['species'].value_counts().plot(kind='pie', colors=pie_colors, autopct='%1.1f%%')
plt.title('Pie Chart')
plt.ylabel('')
plt.show()

# Histogram
plt.figure(figsize=(8, 6))
plt.hist(iris['sepal length (cm)'], bins=20, color='purple')
plt.title('Histogram')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Frequency')
plt.show()

# Heatmap (Correlation)
plt.figure(figsize=(8, 6))
sns.heatmap(iris.corr(), annot=True, cmap='coolwarm')
plt.title('Heatmap (Correlation)')
plt.show()

# Scatter plot
plt.figure(figsize=(8, 6))
scatter_colors = iris['species'].map(bar_colors)
plt.scatter(iris['sepal length (cm)'], iris['petal length (cm)'], c=scatter_colors)
plt.title('Scatter Plot')
plt.xlabel('Sepal Length (cm)')
plt.ylabel('Petal Length (cm)')
plt.show()

# Box Plot
plt.figure(figsize=(8, 6))
box_colors = ['red', 'blue', 'green']
sns.boxplot(x='species', y='sepal width (cm)', data=iris, palette=box_colors)
plt.title('Box Plot')
plt.xlabel('Species')
plt.ylabel('Sepal Width (cm)')
plt.show()